### ISSUE TITLE
Traefik 2

### ISSUE THREAD

**Issue by back-2-95** [druidfi/stonehenge#38]
Refactor Stonehenge to use Traefik 2. This means changes to:

- Traefik configuration
- labels in `docker-compose.yml` files

Maybe some more.

**Comment by back-2-95** [comment]
Create `2.x` branch for this.

**Comment by back-2-95** [comment]
WiP in `2.x` branch.

**Comment by pascalandy** [comment]
Hey, I love your project!!

I'm working hard to migrate my stack on traefik v2. Many due diligence to do as clients depends on my stacks.

Don't be shy to buzz in the future. I'll be glad to review/propose updates :) Meanwhile, I shared [many compose files over this conversation](https://community.containo.us/t/enable-the-secure-dashboard-with-a-pathprefix/3763).

Cheers!

**Comment by back-2-95** [comment]
Thanks @pascalandy !

I still miss error handler where I can show custom error pages to get all the features from 1.x branch using Traefik 1.7. This is what I have currently: https://gist.github.com/back-2-95/ce42754ae29000faaeb3b7df89ae15a3

- middleware for errors
- middleware added to traefik.http.routers.http-catchall.middlewares
- nginx container with custom html page as errors service
- Traefik dashboard shows all is good
- when I try to connect to non-existing local site, it just shows the plain 404 error from Traefik

**Comment by pascalandy** [comment]
I swear, I have the exact same requirement in my backlog :-p

> nginx container with custom html page as errors service

**Comment by back-2-95** [comment]
Just a note to myself:

Switching to use v2 is a bit tricky as projects need to change their labels too. That will result projects in different stages and a user jumping some how between v1 and v2.

**Comment by back-2-95** [comment]
Fixed this for transition perioid (when users possibly using Traefik 1 or 2):

docker-compose.yml service labels for Traefik 1:

```
app:
    labels:
      traefik.enable: true
      traefik.port: 8080
      traefik.frontend.rule: "Host:${DRUPAL_HOSTNAME}"
      traefik.frontend.redirect.entryPoint: https
```

and docker-compose.override.yml service labels for Traefik 2:

```
app:
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"
```
