### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID after stonehenge first install

### ISSUE THREAD

**Issue by carlotodeschini** [druidfi/stonehenge#50]
Just after running
`$ make up`
if I try to access to treafik dashboard page using HTTPS I get a NET::ERR_CERT_AUTHORITY_INVALID error from browser.
I can see the root CA in my "/etc/ssl/certs" dir and I can find the CA in Chrome and Firefox environment. 
I'm running ubuntu 20.04 and docker 20.10.7.
What I'm missing?
Thanks,
tode

**Comment by back-2-95** [comment]
@carlotodeschini can you check with your browser what kind if information it gives about the certificate?

Something likes this when I click the lock on Chrome and get Certificate information:

![CleanShot 2021-08-05 at 12 48 31](https://user-images.githubusercontent.com/1140272/128330164-265f7500-b38f-4ffa-8b72-9305ca7ffd35.png)

**Comment by carlotodeschini** [comment]
Thank you,
I've already checked and I found the TRAEFIK default certificate.
So I substituted this certificate with the one created for my test domain into file "stonehenge/traefik/traefik.dynamic.yml" and now is working correctly.
Is this correct?
tode

**Comment by back-2-95** [comment]
Ah, are you using your own custom domain? I mean other than docker.so ?

**Comment by carlotodeschini** [comment]
Yes, I'm using "todell.lan" domain because we have a catchall rule into our internal DNS. 
Something like *.todell.lan -> "desktop_IP_with_Stonehenge"

**Comment by back-2-95** [comment]
Ok then your changes in `stonehenge/traefik/traefik.dynamic.yml` are correct.
I'd like to have it so that conf would not be needed to change in the future.

**Comment by carlotodeschini** [comment]
> I'd like to have it so that conf would not be needed to change in the future.

Sorry I don't get your request...

**Comment by back-2-95** [comment]
Sorry, no request there =)

I was just thinking that it would be great if `stonehenge/traefik/traefik.dynamic.yml` would not be needed to edit at all when using custom domain.

**Comment by carlotodeschini** [comment]
Ok, yes, I agree with that :thumbsup:
