### ISSUE TITLE
wrong relation in stonehenge/examples/drupal/docker-compose.yml

### ISSUE THREAD

**Issue by VitaliiDubinin** [druidfi/stonehenge#71]
Hi!
To my mind it is mistake and 
image: "druidfi/drupal-test:php-7.4"
should be instead: image: "druidfi/drupal:7.4-test"

**Comment by back-2-95** [comment]
Hi @VitaliiDubinin - I changed the image.

Note thought that new image `druidfi/drupal-test:php-8.0` is a year old and has Drupal 9.2.1.
I need to re-visit test images.
