### ISSUE TITLE
Drupal 8 example

### ISSUE THREAD

**Issue by back-2-95** [druidfi/stonehenge#9]
Create an example where Drupal 8 is raised up with one command.

Now can be just empty installation.

**Comment by back-2-95** [comment]
@Schnitzel is it cool if I use Drupal container from Amazee.io ?

**Comment by Schnitzel** [comment]
@back-2-95 go ahead! But I would suggest to use the new Lagoon Images that can be found here: https://github.com/amazeeio/drupal-example as these are gonna be the ones we will continue to maintain in the future :)

**Comment by back-2-95** [comment]
@Schnitzel I checked the example docker-compose.yml... What is the minimal setup for getting Drupal up & running? I can probably leave solr, varnish and cli away? I want to have the example as simple as possible, and if ppl are interested, they can then go forward and e.g. try Lagoon stuff.

**Comment by Schnitzel** [comment]
@back-2-95 
The minimum is: `cli` (in here we're running drush, composer, etc.), `php`, `nginx`, `mariadb`
The rest can be left away, or just commented as a whole section in the `docker-compose.yml`

**Comment by back-2-95** [comment]
@Schnitzel Ok. I'll do now very simple version with 1 container and with Amazee.io legacy version (which started to work out-of-the-box). And I'll do update to Lagoon version when I have time.
